healthproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    # accounts
    path("", include("accounts.urls", namespace="accounts")),
    # profiles
    path("profile/", include("profiles.urls", namespace="profiles")),
    # plans
    path("plans/", include("plans.urls", namespace="plans")),
    # coaches
    path("coaches/", include("coaches.urls", namespace="coaches")),
    # workoutbank
    path("workouts/", include("workoutbank.urls", namespace="workouts")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

plans/urls.py
from django.urls import path

from .views import create_plan, plan_list, plan_detail


app_name = "plans"

urlpatterns = [
    path("new/<int:coach_id>/", create_plan, name="create_plan"),
    path("list/", plan_list, name="list"),
    path("detail/<int:plan_id>/", plan_detail, name="detail")
]

workoutbank/urls.py
from django.urls import path

from .views import workout_list, workout_detail


app_name = "workoutbank"

urlpatterns = [
    path("list/", workout_list, name="list"),
    path("detail/<int:workout_id>/", workout_detail, name="detail")
]

workoutbank/models.py
import random
import string
import datetime

from django.db import models

from django.contrib.postgres.fields import ArrayField


def get_random_string():
    letters = string.ascii_letters + string.digits + \
        str(datetime.datetime.now().timestamp())
    result = ''.join(random.choice(letters) for i in range(15))
    return result


def workout_image_upload_path(instance, filename):
    random_str = get_random_string()
    file_path = "workouts/{category}/{title}-{random_str}-{filename}".format(
        category=instance.category.title,
        title=instance.title,
        random_str=random_str,
        filename=filename
    )
    return file_path


def workout_cat_image_path(instance, filename):
    random_str = get_random_string()
    file_path = "workouts/categories/{title}-{random_str}-{filename}".format(
        title=instance.title,
        random_str=random_str,
        filename=filename
    )
    return file_path


class WorkoutCategory(models.Model):
    title = models.CharField(max_length=255)
    image = models.ImageField(
        verbose_name="category image", upload_to=workout_cat_image_path, default="")

    class Meta:
        verbose_name = "Category"
        verbose_name_plural = "Categories"

    def __str__(self):
        return self.title


class WorkoutItem(models.Model):
    category = models.ForeignKey(WorkoutCategory, on_delete=models.DO_NOTHING)
    title = models.CharField(max_length=255, blank=False, null=False)
    target_muscles = ArrayField(models.CharField(max_length=255), blank=False)
    description = models.TextField()
    image = models.ImageField(
        verbose_name="workout image", upload_to=workout_image_upload_path)

    def __str__(self):
        return self.title

workoutbank/views.py
from django.shortcuts import render, get_list_or_404, get_object_or_404

from workoutbank.models import WorkoutItem


def workout_list(request):
    workouts = get_list_or_404(WorkoutItem)
    context = {
        "workouts": workouts,
    }
    return render(request, "workoutbank/workoutlist.html", context)


def workout_detail(request, workout_id):
    workout = get_object_or_404(WorkoutItem, pk=workout_id)
    context = {
        "workout": workout
    }
    return render(request, "workoutbank/workoutdetail.html", context)

workoutbank/templates/workoutbank/workoutdetail.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <div class="container">
        <div class="row">
            <p class="h2">{{ workout.title }} از بخش حرکات <span class="badge badge-danger">{{ workout.category }}<span></p>
        </div>
        <div class="row my-3">
            <div class="col-md-7">
                <div class="card">
                    <div class="card-header bg-info">
                        <p class="card-title h3 text-dark">نحوه انجام حرکت <span class="badge badge-danger">{{ workout.title }}<span></p>
                    </div>
                    <img src="{{ workout.image.url }}"/>
                    <div class="card-body bg-secondary">
                        <p class="card-title h3 text-dark">
                            {{ workout.description }}
                        </p>
                    </div>
                </div>
            </div>
            <div class="col-md-5">
                <div class="row">
                    <p class="h3 dark-text">آناتومی عضله {{ workout.category }}</p>
                </div>
                <div class="">
                    <img src="{{ workout.category.image.url }}"/>
                </div>
            </div>
        </div>

        <a href="{% url 'workouts:list' %}" class="btn btn-danger">برگشت به بانک تمرینات</a>
    </div>
{% endblock content %}

workoutbank/templates/workoutbank/workoutlist.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <div class="container">
        <div class="row my-2">
            <form class="form-inline">
                <div class="md-form my-0">
                    <input class="form-control" type="text" placeholder="جستجوی حرکت" aria-label="Search">
                </div>
                <button href="#!" class="btn btn-primary btn-md my-0 ml-sm-2" type="submit">جستجو</button>
            </form>
        </div>
        <div class="row my-3">
            <p class="h3">برای دیدن جزئیات، توضیحات و مطالب علمی هر تمرین بر روی تمرین مربوطه کلیک کنید.</p>
        </div>
        <div class="row">
            <div class="col-md-5 p-4 bg-primary">
                {% for workout in workouts %}
                    <div class="">
                        <a class="" href="{% url 'workoutbank:detail' workout_id=workout.pk %}">
                            <span class="badge badge-light">{{forloop.counter}}</span> <p class="d-inline h3 text-light">{{ workout.title }}</p>
                        </a>
                        <span class="badge badge-light">{{ workout.category.title }}</span>
                    </div>
                {% endfor %}
            </div>
            <div class="col-md-7">
                <img src="{% static 'workoutbank/img/anatomy.jpg' %}"/>
            </div>
        </div>
    </div>
{% endblock content %}