accounts/urls.py
from django.urls import path

from .views import login, logout, register, dashboard, user_profile

app_name = "accounts"

urlpatterns = [
    path("login/", login, name="login"),
    path("logout/", logout, name="logout"),
    path("register/", register, name="register"),
    path("dashboard/", dashboard, name="dashboard"),
    path("profile/", user_profile, name="user_profile")
]

healthproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    # accounts
    path("", include("accounts.urls", namespace="accounts")),
    # profiles
    path("profile/", include("profiles.urls", namespace="profiles")),
    # plans
    path("plans/", include("plans.urls", namespace="plans")),
    # coaches
    path("coaches/", include("coaches.urls", namespace="coaches")),
    # workoutbank
    path("workouts/", include("workoutbank.urls", namespace="workouts")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

plans/urls.py
from django.urls import path

from .views import create_plan, plan_list, plan_detail


app_name = "plans"

urlpatterns = [
    path("new/<int:coach_id>/", create_plan, name="create_plan"),
    path("list/", plan_list, name="list"),
    path("detail/<int:plan_id>/", plan_detail, name="detail")
]

profiles/urls.py
from django.urls import path

from .views import update_client_information

app_name = "profiles"

urlpatterns = [
    path("update/", update_client_information, name="update_client_information")
]

workoutbank/urls.py
from django.urls import path

from .views import workout_list, workout_detail


app_name = "workoutbank"

urlpatterns = [
    path("list/", workout_list, name="list"),
    path("detail/<int:workout_id>/", workout_detail, name="detail")
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager

from profiles.models import Profile


class MyAccountManager(BaseUserManager):
    def create_user(self, email, username, first_name, last_name, password=None):
        if not email or not username or not first_name or not last_name or not password:
            raise ValueError(
                "Users must have email, username, password, first name and last name")
        user = self.model(
            email=self.normalize_email(email),
            username=username,
            first_name=first_name,
            last_name=last_name
        )
        user.set_password(password)
        try:
            user.save(using=self._db)
            return user
        except:
            raise ValueError("Couldn't create user.")

    def create_superuser(self, email, username, first_name, last_name, password):
        if not email or not username or not first_name or not last_name or not password:
            raise ValueError(
                "Users must have email, username, password, first name and last name")
        user = self.model(
            email=self.normalize_email(email),
            username=username,
            first_name=first_name,
            last_name=last_name,
        )
        user.set_password(password)
        user.is_admin = True
        user.is_staff = True
        user.is_superuser = True
        try:
            user.save(using=self._db)
            return user
        except:
            raise ValueError("Couldn't create superuser.")

    def coaches(self):
        coaches = Account.objects.filter(type=Account.Types.COACH)
        return coaches


class Account(AbstractBaseUser):

    class Types(models.TextChoices):
        COACH = "COACH", "Coach"
        CLIENT = "CLIENT", "Client"

    type = models.CharField(verbose_name="Type", max_length=10,
                            choices=Types.choices, default=Types.CLIENT)

    email = models.EmailField(verbose_name="email",
                              max_length=100, unique=True)
    username = models.CharField(max_length=30, unique=True)
    first_name = models.CharField(verbose_name="first name", max_length=30)
    last_name = models.CharField(verbose_name="last name", max_length=40)
    date_joined = models.DateTimeField(
        verbose_name="date joined", auto_now_add=True)
    last_login = models.DateTimeField(verbose_name="last login", auto_now=True)
    is_admin = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)

    profile = models.OneToOneField(
        Profile, on_delete=models.CASCADE, null=True, blank=True)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = ["username", "first_name", "last_name"]

    objects = MyAccountManager()

    def __str__(self):
        return self.email

    def has_perm(self, perm, obj=None):
        return self.is_admin

    def has_module_perms(self, app_label):
        return True


class CoachManager(models.Manager):
    def get_queryset(self, *args, **kwargs):
        return super().get_queryset(*args, **kwargs).filter(type=Account.Types.COACH)


class CoachExtra(models.Model):
    user = models.OneToOneField(Account, on_delete=models.CASCADE)
    workout_price = models.DecimalField(
        max_digits=15, decimal_places=3, default=0.000)
    meal_price = models.DecimalField(
        max_digits=15, decimal_places=3, default=0.000)


class Coach(Account):
    objects = CoachManager()

    @property
    def extra(self):
        return self.coachextra

    class Meta:
        proxy = True

    def save(self, *args, **kwargs):
        if not self.pk:
            self.type = Account.Types.COACH
        return super().save(*args, **kwargs)


class ClientManager(models.Manager):
    def get_queryset(self, *args, **kwargs):
        return super().get_queryset(*args, **kwargs).filter(type=Account.Types.CLIENT)


class Client(Account):
    objects = ClientManager()

    class Meta:
        proxy = True

    def save(self, *args, **kwargs):
        if not self.pk:
            self.type = Account.Types.CLIENT
        return super().save(*args, **kwargs)

accounts/forms.py
from django import forms

from .models import Account


class LoginForm(forms.Form):
    email = forms.CharField(max_length=100)
    password = forms.CharField(max_length=50, widget=forms.PasswordInput)

    def __init__(self, *args, **kwargs):
        super(LoginForm, self).__init__(*args, **kwargs)

        fieldsMap = {
            "email": "ایمیل",
            "password": "پسورد"
        }
        # Assigning class and placeholder and removeing label from fields
        for k, v in self.fields.items():
            self.fields[k].label = ""
            v.widget.attrs['class'] = 'input'
            if k in fieldsMap:
                v.widget.attrs['placeholder'] = fieldsMap[k]

    class Meta:
        model = Account
        fields = ["email", "password"]


class RegistrationForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(RegistrationForm, self).__init__(*args, **kwargs)

        fieldsMap = {
            "first_name": "نام",
            "last_name": "خانوادگی",
            "username": "نام کاربری",
            "email": "ایمیل",
            "password": "پسورد"
        }
        # Assigning class and placeholder and removeing label from fields
        for k, v in self.fields.items():
            self.fields[k].label = ""
            v.widget.attrs['class'] = 'input'
            if k in fieldsMap:
                v.widget.attrs['placeholder'] = fieldsMap[k]

    class Meta:
        model = Account
        fields = ["first_name", "last_name", "username", "email", "password"]


class UpdateClientInformation(forms.ModelForm):
    class Meta:
        model = Account
        fields = ["first_name", "last_name"]

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login as auth_login, logout as auth_logout, authenticate
from django.contrib.auth import get_user_model
from django.shortcuts import get_object_or_404
from django.contrib.auth.decorators import login_required

from .forms import LoginForm, RegistrationForm, UpdateClientInformation
from .decorators import authorized_user


@authorized_user
def login(request):
    context = {}
    if request.POST:
        form = LoginForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data.get("email")
            password = form.cleaned_data.get("password")
            user = authenticate(request, username=email, password=password)
            if user:
                if user.type == "CLIENT":
                    auth_login(request, user)
                    return redirect("accounts:dashboard")
                elif user.type == "COACH":
                    auth_login(request, user)
                    return redirect("coaches:dashboard")
            else:
                return redirect("accounts:register")
        else:
            context["form"] = form
    else:
        form = LoginForm()
        context["form"] = form
    return render(request, "accounts/login.html", context)


@login_required(login_url="accounts:login")
def logout(request):
    auth_logout(request)
    return redirect("accounts:login")


def register(request):
    context = {}
    if request.POST:
        form = RegistrationForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            email = form.cleaned_data["email"]
            password = form.cleaned_data["password"]
            user.set_password(password)
            user.type = "CLIENT"
            form.save()
            return redirect("accounts:login")
        else:
            context["form"] = form
    else:
        form = RegistrationForm()
        context["form"] = form
    return render(request, "accounts/register.html", context)


@login_required(login_url="accounts:login")
def dashboard(request):
    context = {}
    if request.user.is_authenticated:
        coaches = get_user_model().objects.coaches()
        context["coaches"] = coaches
    else:
        return redirect("accounts:login")
    return render(request, "accounts/dashboard.html", context)


@login_required(login_url="accounts:login")
def user_profile(request):
    if not request.user.is_authenticated:
        return redirect("accounts:login")
    context = {}
    if request.user.profile and request.user.type == "CLIENT":
        context["profile"] = request.user.profile
    return render(request, "accounts/user_profile.html", context)

accounts/templates/accounts/dashboard.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}

<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Portal</title>
    <meta http-equiv="X-UA-Compatible" content="IE=Edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">
    <meta name="format-detection" content="telephone=no">
    <meta name="description" content="Page description">
    <!--Twitter Card data-->
    <meta name="twitter:card" content="summary">
    <meta name="twitter:site" content="@publisher_handle">
    <meta name="twitter:title" content="Page Title">
    <meta name="twitter:description" content="Page description less than 200 characters">
    <meta name="twitter:creator" content="@author_handle">
    <meta name="twitter:image" content="http://www.example.com/image.jpg">
    <!--Open Graph data-->
    <meta property="og:title" content="Title Here">
    <meta property="og:type" content="article">
    <meta property="og:url" content="http://www.example.com/">
    <meta property="og:image" content="http://example.com/image.jpg">
    <meta property="og:description" content="Description Here">
    <meta property="og:site_name" content="Site Name, i.e. Moz">
    <meta property="fb:admins" content="Facebook numeric ID">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'accounts/img/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'accounts/img/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'accounts/img/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'accounts/img/site.webmanifest' %}">
    <link rel="mask-icon" href="{% static 'accounts/img/safari-pinned-tab.svg'%}" color="#5bbad5">
    <meta name="msapplication-TileColor" content="#da532c">
    <meta name="theme-color" content="#ffffff">
    <link href="https://fonts.googleapis.com/css?family=Karla:400,700&amp;display=swap" rel="stylesheet">
    <link rel="stylesheet" media="all" href="{% static 'accounts/dashboard/css/styles.css' %}">
  </head>
  <body>
    {% block title_head %} پنل کاربری {% endblock title_head %}

  {% block navbar %}
  <nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
  <a class="navbar-brand" href="#">FITNO</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="#">برنامه‌های من</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'accounts:user_profile' %}">مشخصات</a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="#">لیست مربیان<span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'workoutbank:list' %}">بانک تمرینات ورزشی</a>
      </li>
    </ul>
  </div>
  <div>
    <a href="{% url 'accounts:logout' %}" class="navbar-brand">خروج از سیستم</a>
  </div>
</nav>
  {% endblock navbar %}
    {% block content %}
    <div class="page">
        <div class="container">
            <div class="row mx-n5">
                {% for coach in coaches %}
                  <div class="col-md-4 px-6 mb-2">
                      <div class="p-3 border bg-light text-dark">
                          <div class="card">
                              <img class="card-img-top" src="{% static 'accounts/dashboard/img/coach-default.jpg' %}" alt="مربی">
                              <div class="card-body">
                                  <h5 class="card-title">{{ coach.first_name }} {{ coach.last_name }}</h5>
                                  <ul class="list-unstyled">
                                      <li class="list-group-item p-1">{{ coach.profile.coachprofileextra.education }}</li>
                                  </ul>
                                  <ul class="list-inline mt-2">
                                      <li class="list-inline-item">برنامه غذایی: <span class="badge"> {{ coach.coachextra.meal_price|floatformat:3|intcomma }} </span></li>
                                      <li class="list-inline-item">برنامه تمرینی: <span class="badge">{{ coach.coachextra.workout_price|floatformat:3|intcomma }}</span></li>
                                  </ul>
                                  <div class="mt-3">
                                      <a href="{% url 'plans:create_plan' coach_id=coach.pk %}" class="btn text-light btn-dark">درخواست برنامه</a>
                                  </div>
                              </div>
                          </div>
                    </div>
                  </div>
                {% endfor %}
            </div>
        </div>
    </div>
    {% endblock content %}
  </body>
</html>

accounts/templates/accounts/login.html
{% load static %}

<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Portal</title>
    <meta http-equiv="X-UA-Compatible" content="IE=Edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">
    <meta name="format-detection" content="telephone=no">
    <meta name="description" content="Page description">
    <!--Twitter Card data-->
    <meta name="twitter:card" content="summary">
    <meta name="twitter:site" content="@publisher_handle">
    <meta name="twitter:title" content="Page Title">
    <meta name="twitter:description" content="Page description less than 200 characters">
    <meta name="twitter:creator" content="@author_handle">
    <meta name="twitter:image" content="http://www.example.com/image.jpg">
    <!--Open Graph data-->
    <meta property="og:title" content="Title Here">
    <meta property="og:type" content="article">
    <meta property="og:url" content="http://www.example.com/">
    <meta property="og:image" content="http://example.com/image.jpg">
    <meta property="og:description" content="Description Here">
    <meta property="og:site_name" content="Site Name, i.e. Moz">
    <meta property="fb:admins" content="Facebook numeric ID">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'accounts/img/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'accounts/img/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'accounts/img/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'accounts/img/site.webmanifest' %}">
    <link rel="mask-icon" href="{% static 'accounts/img/safari-pinned-tab.svg'%}" color="#5bbad5">
    <meta name="msapplication-TileColor" content="#da532c">
    <meta name="theme-color" content="#ffffff">
    <link href="https://fonts.googleapis.com/css?family=Karla:400,700&amp;display=swap" rel="stylesheet">
    <link rel="stylesheet" media="all" href="{% static 'accounts/css/app.css' %}">
  </head>
  <body>
    <div class="page page_login">
      <form class="form" action={% url 'accounts:login' %} method="POST">
      {% csrf_token %}
        <div class="form__container">
          <div class="logo"><img class="logo__pic" src="{% static 'accounts/img/logo.svg' %}" width="45"></div>
          <div class="fieldset">
            {% comment %} <div class="field"><input class="input" type="email" placeholder="ایمیل" required></div>
            <div class="field"><input class="input" type="password" placeholder="پسورد" required></div> {% endcomment %}
            {{ form }}
          </div><button class="btn">ورود به سیستم</button>
          <div class="text">پسوردتون رو فراموش کردین؟ <a href="#">برش گردون</a></div>
        </div>
        <div class="form__footer">حساب کاربری ندارید؟ <a href="index.html">یکی بسازید</a></div>
      </form>
      {% comment %} <div class="about">Website template by ⚡ <a href="https://niceverynice.com">Nice, Very Nice</a></div> {% endcomment %}
    </div>
  </body>
</html>

accounts/templates/accounts/register.html
{% load static %}

<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Portal</title>
    <meta http-equiv="X-UA-Compatible" content="IE=Edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">
    <meta name="format-detection" content="telephone=no">
    <meta name="description" content="Page description">
    <!--Twitter Card data-->
    <meta name="twitter:card" content="summary">
    <meta name="twitter:site" content="@publisher_handle">
    <meta name="twitter:title" content="Page Title">
    <meta name="twitter:description" content="Page description less than 200 characters">
    <meta name="twitter:creator" content="@author_handle">
    <meta name="twitter:image" content="http://www.example.com/image.jpg">
    <!--Open Graph data-->
    <meta property="og:title" content="Title Here">
    <meta property="og:type" content="article">
    <meta property="og:url" content="http://www.example.com/">
    <meta property="og:image" content="http://example.com/image.jpg">
    <meta property="og:description" content="Description Here">
    <meta property="og:site_name" content="Site Name, i.e. Moz">
    <meta property="fb:admins" content="Facebook numeric ID">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'accounts/img/apple-touch-icon.png'%}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'accounts/img/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'accounts/img/favicon-16x16.png' %}">
    <link rel="manifest" href="img/site.webmanifest">
    <link rel="mask-icon" href="img/safari-pinned-tab.svg" color="#5bbad5">
    <meta name="msapplication-TileColor" content="#da532c">
    <meta name="theme-color" content="#ffffff">
    <link href="https://fonts.googleapis.com/css?family=Karla:400,700&amp;display=swap" rel="stylesheet">
    <link rel="stylesheet" media="all" href="{% static 'accounts/css/app.css' %}">
  </head>
  <body>
    <div class="page">
      <form class="form" action="{% url 'accounts:register' %}" method="POST">
      {% csrf_token %}
        <div class="form__container">
          <div class="logo"><img class="logo__pic" src="{% static 'accounts/img/logo.svg' %}" width="45"></div>
          <div class="fieldset">
            {% comment %} <div class="field"><input class="input" type="text" placeholder="نام" name="first_name" required></div>
            <div class="field"><input class="input" type="text" placeholder="نام خانوادگی" name="last_name" required></div>
            <div class="field"><input class="input" type="email" placeholder="ایمیل" name="email" required></div>
            <div class="field"><input class="input" type="password" placeholder="پسورد" name="password" required></div>
            <div class="field"><input class="input" type="password" placeholder="تکرار کلمه عبور" name="repassword" required></div> {% endcomment %}
            {{form}}
          </div><button class="btn">Sign up</button>
          <div class="text">با ساختن حساب کاربری شما با <a href="#">قوانین</a> و <a href="#">سیاست کاری</a> ما موافق هستید</div>
        </div>
        <div class="form__footer">از قبل حساب کاربری در فیتنو دارید؟ <a href="{% url 'accounts:login' %}">وارد شوید</a></div>
      </form>
      {% comment %} <div class="about">Website template by ⚡ <a href="https://niceverynice.com">Nice, Very Nice</a></div> {% endcomment %}
    </div>
  </body>
</html>

accounts/templates/accounts/user_profile.html
{% extends 'base.html' %}
{% load static %}

{% block title_head %}
پروفایل
{% endblock title_head %}

{% block content %}
  <div class="main-content">
    <!-- Top navbar -->
    <nav class="navbar navbar-top navbar-expand-md navbar-dark" id="navbar-main">
      <div class="container-fluid">
        <!-- Brand -->
        <a class="h4 mb-0 text-white text-uppercase d-none d-lg-inline-block" href="https://www.creative-tim.com/product/argon-dashboard" target="_blank">پنل کاربری</a>
        <!-- User -->
      </div>
    </nav>
    <!-- Header -->
    <div class="header pb-8 pt-5 pt-lg-8 d-flex align-items-center" style="min-height: 600px; background: url({% static 'accounts/img/Gym-register.jpg' %}); background-size: cover; background-position: center top;">
      <!-- Mask -->
      <span class="mask bg-gradient-default opacity-8"></span>
      <!-- Header container -->
      <div class="container-fluid d-flex align-items-center">
        <div class="row">
          <div class="col-lg-7 col-md-10">
            <h1 class="display-2 text-white">سلام {{ request.user.first_name }}</h1>
            <p class="text-white mt-0 mb-5">ابینجا پروفایل شماست. اینجا می‌تونین برخی از اطلاعات خودتون رو تغییر بدین. اطلاعات را به درستی وارد کنید زیرا که مربی عزیز شما به برخی از انها دسترسی خواهد داشت.</p>
          </div>
        </div>
      </div>
    </div>
    <!-- Page content -->
    <div class="container-fluid mt--7">
    <form action="{% url 'profiles:update_client_information' %}" method="POST" enctype="multipart/form-data">
      <div class="row">
        <div class="col-xl-4 order-xl-2 mb-5 mb-xl-0">
          <div class="card card-profile shadow">
            <div class="row justify-content-center">
              <div class="col-lg-3 order-lg-2">
                <div class="card-profile-image">
                  <a href="#">
                    {% if request.user.profile.image %}
                      <img src="{{ request.user.profile.image.url }}" class="rounded-circle">
                    {% else %}
                      <img src="{% static 'accounts/img/default.jpeg' %}" class="rounded-circle">
                    {% endif %}
                  </a>
                </div>
              </div>
              
              <input type="file" name="image"/>
            </div>
            <div class="card-header text-center border-0 pt-8 pt-md-4 pb-0 pb-md-4">
              <div class="d-flex justify-content-between">
                {% comment %} <a href="#" class="btn btn-sm btn-info mr-4">ارتباط با ایمیل</a>
                <a href="#" class="btn btn-sm btn-default float-right">Message</a> {% endcomment %}
              </div>
            </div>
            <div class="card-body pt-0 pt-md-4">
              <div class="row">
                <div class="col">
                  <div class="card-profile-stats d-flex justify-content-center mt-md-5">
                    <div>
                      <span class="heading">۲۰</span>
                      <span class="description">تعداد برنامه‌ها</span>
                    </div>
                    <div>
                      <span class="heading">۱۲۳۴۰</span>
                      <span class="description">روز‌های تمرین شما</span>
                    </div>
                  </div>
                </div>
              </div>
              <div class="text-center">
                <h3>
                  {{ request.user.first_name }} {{ request.user.last_name }}<span class="font-weight-light">, ۲۰</span>
                </h3>
                <div class="h5 font-weight-300">
                  <i class="ni location_pin mr-2"></i>{{ profile.location }}
                </div>
                <div class="h5 mt-4">
                  <i class="ni business_briefcase-24 mr-2"></i>برنامه‌نویس - علاقه‌مند به فیزیولوژی
                </div>
                <hr class="my-4">
                <p>
                    امیر هستم علاقه‌مند به برنامه‌نویس و در عین حال بیکار و علاقه‌مند به فیزیولوژی فقط.
                </p>
                <a href="#">Show more</a>
              </div>
            </div>
          </div>
        </div>
        <div class="col-xl-8 order-xl-1">
          <div class="card bg-secondary shadow">
            <div class="card-header bg-white border-0">
              <div class="row align-items-center">
                <div class="col-8">
                  <h3 class="mb-0">حساب من</h3>
                </div>
              </div>
            </div>
            <div class="card-body">
              {% csrf_token %}
                <h6 class="heading-small text-muted mb-4">اطلاعات کاربری</h6>
                <div class="pl-lg-4">
                  <div class="row">
                    <div class="col-lg-6">
                      <div class="form-group focused">
                        <label class="form-control-label" for="input-username">نام کاربری</label>
                        <input type="text" id="input-username" class="form-control form-control-alternative" disabled placeholder="Username" value="{{ request.user.username }}">
                      </div>
                    </div>
                    <div class="col-lg-6">
                      <div class="form-group">
                        <label class="form-control-label" for="input-email">ایمیل</label>
                        <input type="email" id="input-email" class="form-control form-control-alternative" disabled placeholder="{{ request.user.email }}">
                      </div>
                    </div>
                  </div>
                  <div class="row">
                    <div class="col-lg-6">
                      <div class="form-group focused">
                        <label class="form-control-label" for="input-first-name">نام</label>
                        <input type="text" id="input-first-name" class="form-control form-control-alternative" name="first_name" placeholder="First name" value="{{ request.user.first_name }}">
                      </div>
                    </div>
                    <div class="col-lg-6">
                      <div class="form-group focused">
                        <label class="form-control-label" for="input-last-name">نام خانوادگی</label>
                        <input type="text" id="input-last-name" class="form-control form-control-alternative" name="last_name" placeholder="Last name" value="{{ request.user.last_name }}">
                      </div>
                    </div>
                    <div class="col-lg-6">
                      <div class="form-group focused">
                        <label class="form-control-label" for="input-last-name">محل زندگی</label>
                        <input type="text" id="input-last-name" class="form-control form-control-alternative" name="location" placeholder="Last name" value="{{ profile.location }}">
                      </div>
                    </div>
                    <div class="col-lg-6">
                      <div class="form-group focused">
                        <label class="form-control-label" for="input-last-name">شغل</label>
                        <input type="text" id="input-last-name" class="form-control form-control-alternative" name="job" placeholder="Last name" value="{{ profile.job }}">
                      </div>
                    </div>
                  </div>
                </div>
                <hr class="my-4">
                <!-- Description -->
                <h6 class="heading-small text-muted mb-4">درباره من</h6>
                <div class="pl-lg-4">
                  <div class="form-group focused">
                    <label>من کی هستم؟</label>
                    <textarea rows="4" class="form-control form-control-alternative" placeholder="A few words about you ...">A beautiful Dashboard for Bootstrap 4. It is Free and Open Source.</textarea>
                  </div>
                </div>
                <div>
                  <button type="submit" class="btn btn-info">اعمال تغییرات</button>
                </div>
            </div>
          </div>
        </div>

        
      </div>
    </div>
    </form>
  </div>
  <footer class="footer">
    <div class="row align-items-center justify-content-xl-between">
      {% comment %} <div class="col-xl-6 m-auto text-center">
        <div class="copyright">
          <p>Made with <a href="https://www.creative-tim.com/product/argon-dashboard" target="_blank">Argon Dashboard</a> by Creative Tim</p>
        </div>
      </div> {% endcomment %}
    </div>
  </footer>
{% endblock content %}