coaches/urls.py
from django.urls import path

from .views import dashboard, new_requests, create_plan, create_pdf
from profiles.views import update_coach_information


app_name = "coaches"

urlpatterns = [
    path("dashboard/", dashboard, name="dashboard"),
    path("requests/list/", new_requests, name="new_requests"),
    path("requests/create/<int:request_id>/", create_plan, name="create_plan"),
    path("requests/create/pdf/", create_pdf, name="create_pdf"),
    path("update/", update_coach_information, name="update_coach_information"),
]

healthproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    # accounts
    path("", include("accounts.urls", namespace="accounts")),
    # profiles
    path("profile/", include("profiles.urls", namespace="profiles")),
    # plans
    path("plans/", include("plans.urls", namespace="plans")),
    # coaches
    path("coaches/", include("coaches.urls", namespace="coaches")),
    # workoutbank
    path("workouts/", include("workoutbank.urls", namespace="workouts")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

plans/urls.py
from django.urls import path

from .views import create_plan, plan_list, plan_detail


app_name = "plans"

urlpatterns = [
    path("new/<int:coach_id>/", create_plan, name="create_plan"),
    path("list/", plan_list, name="list"),
    path("detail/<int:plan_id>/", plan_detail, name="detail")
]

plans/models.py
from django.db import models
from django.contrib.auth import get_user_model

from accounts.models import Coach, Client
from sizes.models import Size
from client_images.models import ClientImage

FOOD_NATURE_CHOICES = (
    ("VEGETARIAN", "گیاه‌خوار"),
    ("NONVEGETARIAN",  "با خوردن گوشت مشکلی ندارم.")
)


class Plan(models.Model):
    client = models.ForeignKey(
        Client, on_delete=models.DO_NOTHING, related_name="client")
    coach = models.ForeignKey(
        Coach, on_delete=models.DO_NOTHING, related_name="coach")
    size = models.ForeignKey(Size, on_delete=models.DO_NOTHING, null=True)
    image = models.ForeignKey(
        ClientImage, on_delete=models.DO_NOTHING, null=True)
    food_nature = models.CharField(
        max_length=13, choices=FOOD_NATURE_CHOICES, default="NONVEGETARIAN")
    created_at = models.DateTimeField(auto_now_add=True)
    status = models.BooleanField(verbose_name="Sent", default=False)

    def __str__(self):
        return self.client.email

plans/forms.py
from django.forms import ModelForm

from .models import Plan


class PlanNatureFoodForm(ModelForm):
    class Meta:
        model = Plan
        fields = ("food_nature",)

plans/views.py
from django.shortcuts import render, get_object_or_404, get_list_or_404
from django.contrib.auth.decorators import login_required

from .models import Plan
from accounts.models import Coach
from .forms import PlanNatureFoodForm
from sizes.forms import SizesForm
from client_images.forms import ClientImageForm


@login_required(login_url="accounts:login")
def create_plan(request, coach_id):
    size_form = SizesForm(request.POST or None)
    plan_form = PlanNatureFoodForm(request.POST or None)
    image_form = ClientImageForm(request.POST or None, request.FILES or None)
    coach = get_object_or_404(Coach, pk=coach_id)
    if request.POST:
        if size_form.is_valid() and plan_form.is_valid() and image_form.is_valid():
            size = size_form.save(commit=False)
            size.client = request.user
            size.save()

            plan = plan_form.save(commit=False)
            image = image_form.save(commit=False)
            image.plan = plan

            plan.client = request.user
            plan.coach = coach
            plan.size = size
            plan.image = image

            image.save()
            plan.save()

        else:
            print("ERRORS IN FORMS")
    context = {
        "size_form": size_form,
        "plan_form": plan_form,
        "image_form": image_form,
        "coach": coach
    }
    return render(request, "plans/index.html", context)


@login_required(login_url="accounts:login")
def plan_list(request):
    context = {}
    plans = get_list_or_404(Plan, client=request.user)
    if plans:
        context["plans"] = plans
    return render(request, "plans/list.html", context)


@login_required(login_url="accounts:login")
def plan_detail(request, plan_id):
    context = {}
    plan = get_object_or_404(Plan, client=request.user, pk=plan_id)
    if plan:
        context["plan"] = plan
    return render(request, "plans/details.html", context)

plans/templates/plans/details.html
{% extends 'base.html' %}

{% block title_head %} جزئیات درخواست {% endblock title_head %}

{% block content %}
    <div class="container p-3">
        {% if plan %}
            <div class="row mb-5">
                <div class="col-md-10 mx-auto">
                    <div class="card bg-warning">
                        <div class="card-header">
                            <h4 class="card-title">جزئیات درخواست برنامه</h4>
                            <h2 class="card-title text-dark">مربی: {{ plan.coach.first_name }} {{ plan.coach.last_name }} 
                                <img src={{ plan.coach.profile.image.url }} width="300" height="300"/>
                            </h2>
                        </div>
                        <div class="card-body">
                            <p class="card-body">
                                تاریخ ارسال: {{ plan.created_at }}
                            </p>
                            <p>تصاویر ارسال شده برای درخواست: <img src="{{ plan.image.front.url }}" /> <img src="{{ plan.image.side.url }}" /> <img src="{{ plan.image.back.url }}" /> </p>
                        </div>
                        <a class="btm btn-danger p-3 w-50" href="{% url 'plans:list' %}">برگشتن به داشبورد</a>
                    </div>
                </div>
            </div>
        {% else %}
            <div class="row">
                <h2 class="text-dark bg-info">شما هیچ درخواست ثبت شده‌ای ندارید.</h2>
                <a class="btm btn-danger" href="{% url 'plans:list' %}">برگشتن به داشبورد</a>
            </div>
        {% endif %}
    </div>
{% endblock content %}

plans/templates/plans/index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="main">
        <div class="container">
            <div class="signup-content">
                <div class="signup-img">
                    <img src="{% static 'plans/images/form-img.jpg' %}" alt="">
                    <div class="signup-img-content">
                        <h2>ثبت درخواست برنامه جدید</h2>
                        <p>لطفا اطلاعات رو به دقت و صحیح پر کنید.</p>
                    </div>
                </div>
                <div class="signup-form">
                <div class="bg-warning mt-4 p-3">
                    <p>{{request.user.first_name}} عزیز شما در حال ارسال درخواست برنامه برای مربی {{ coach.first_name }} {{ coach.last_name }} هستید.</p>
                </div>
                    <form method="POST" class="register-form" id="register-form" enctype="multipart/form-data"> {% csrf_token %}
                        <div class="form-row">
                            <div class="form-group">
                                {{ size_form }}
                            </div>
                            <div class="form-group">
                                <div class="form-select">
                                    <div class="label-flex">
                                        <label for="gender">جنسیت</label>
                                    </div>
                                   <div class="form-radio-group">            
                                        <div class="form-radio-item">
                                            <input type="radio" name="gender" id="male" checked>
                                            <label for="cash">مرد</label>
                                            <span class="check"></span>
                                        </div>
                                        <div class="form-radio-item">
                                            <input type="radio" name="gender" id="female">
                                            <label for="cash">زن</label>
                                            <span class="check"></span>
                                        </div>
                                        <div class="form-radio-item">
                                            <input type="radio" name="gender" id="other">
                                            <label for="cheque">دیگر</label>
                                            <span class="check"></span>
                                        </div>
                                    </div>
                                </div>
                                <div class="form-select">
                                    <div class="label-flex">
                                        <label for="food_nature">طبع غذایی</label>
                                        <a href="#" class="form-link">جزئیات غذایی</a>
                                    </div>
                                    <div class="select-list">
                                        <select name="food_nature" {% comment %} id="meal_preference"{% endcomment %}>
                                            {% for k, v in plan_form.fields.food_nature.choices %}
                                                <option value="{{ k }}" {% if plans_form.fields.food_nature.value == x %}selected{% endif %}>{{ v }}</option>
                                            {% endfor %}
                                        </select>
                                    </div>
                                </div>
                                {{ image_form }}
                                <div class="form-radio mt-5">
                                    <div class="label-flex">
                                        <label for="payment">پرداخت</label>
                                        <a href="#" class="form-link">جزئیات پرداخت</a>
                                    </div>
                                    <div class="form-radio-group">            
                                        <div class="form-radio-item">
                                            <input type="radio" name="payment" id="cash" checked>
                                            <label for="cash">پرداخت انلاین</label>
                                            <span class="check"></span>
                                        </div>
                                        <div class="form-radio-item">
                                            <input type="radio" name="payment" id="cheque">
                                            <label for="cheque">واریز به کارت</label>
                                            <span class="check"></span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="form-submit">
                            <input type="submit" value="ثبت درخواست" class="submit" id="submit" name="submit" />
                            <input type="submit" value="ریست کردن" class="submit" id="reset" name="reset" />
                        </div>
                    </form>
                </div>
            </div>
        </div>

    </div>
{% endblock content %}

plans/templates/plans/list.html
{% extends 'base.html' %}

{% block title_head %} لیست درخواست‌های من {% endblock title_head %}

{% block content %}
    <div class="container p-3">
        {% if plans %}
            {% for plan in plans %}
                <div class="row mb-5">
                    <div class="col-md-10 mx-auto">
                        <div class="card bg-warning">
                            <div class="card-header">
                                <h4 class="card-title">درخواست برنامه</h5>
                                <h2 class="card-title text-dark">مربی: {{ plan.coach.first_name }} {{ plan.coach.last_name }} </h5>
                            </div>
                            <div class="card-body">
                                <p class="card-body">
                                    شما در تاریخ {{plan.created_at}} به مربی مذکور درخواست ارسال کردین. برای دیدن جزئیات درخواست روی دیدن جزئیات برنامه کلیک کنید.
                                </p>
                                <a href="{% url 'plans:detail' plan_id=plan.pk %}" class="btn btn-default">دیدن جزئیات برنامه</a>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        {% else %}
            <div class="row">
                <h2 class="text-dark bg-info">شما هیچ درخواست ثبت شده‌ای ندارید.</h2>
                <a class="btm btn-danger" href="{% url 'accounts:dashboard' %}">برگشتن به داشبورد</a>
            </div>
        {% endif %}
    </div>
{% endblock content %}