coaches/urls.py
from django.urls import path

from .views import dashboard, new_requests, create_plan, create_pdf
from profiles.views import update_coach_information


app_name = "coaches"

urlpatterns = [
    path("dashboard/", dashboard, name="dashboard"),
    path("requests/list/", new_requests, name="new_requests"),
    path("requests/create/<int:request_id>/", create_plan, name="create_plan"),
    path("requests/create/pdf/", create_pdf, name="create_pdf"),
    path("update/", update_coach_information, name="update_coach_information"),
]

healthproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    # accounts
    path("", include("accounts.urls", namespace="accounts")),
    # profiles
    path("profile/", include("profiles.urls", namespace="profiles")),
    # plans
    path("plans/", include("plans.urls", namespace="plans")),
    # coaches
    path("coaches/", include("coaches.urls", namespace="coaches")),
    # workoutbank
    path("workouts/", include("workoutbank.urls", namespace="workouts")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

plans/urls.py
from django.urls import path

from .views import create_plan, plan_list, plan_detail


app_name = "plans"

urlpatterns = [
    path("new/<int:coach_id>/", create_plan, name="create_plan"),
    path("list/", plan_list, name="list"),
    path("detail/<int:plan_id>/", plan_detail, name="detail")
]

coaches/forms.py
from django.forms import ModelForm

from accounts.models import Account, CoachExtra
from profiles.models import Profile, CoachProfile, CoachProfileExtra


class UpdateCoachInformation(ModelForm):
    class Meta:
        model = Account
        fields = ["first_name", "last_name"]


class UpdateCoachExtraInformation(ModelForm):
    class Meta:
        model = CoachExtra
        fields = ["workout_price", "meal_price"]


class UpdateCoachProfile(ModelForm):
    class Meta:
        model = Profile
        fields = ["location", "job"]


class UpdateCoachProfileExtra(ModelForm):
    class Meta:
        model = CoachProfileExtra
        fields = ["education", "image", "panel_image"]

coaches/views.py
from io import BytesIO
import json
import tempfile

from django.http import HttpResponse
from django.shortcuts import render, get_list_or_404, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib.staticfiles import finders
from django.conf import settings
from django.views.decorators.csrf import csrf_exempt
from django.template.loader import get_template, render_to_string
from django.views.generic import View

from workoutbank.models import WorkoutItem

from xhtml2pdf import pisa

from weasyprint import HTML

from plans.models import Plan
from accounts.decorators import coach_required


@login_required(login_url="accounts:login")
@coach_required
def dashboard(request):
    plans_num = Plan.objects.filter(coach=request.user).count()
    context = {
        "plans_num": plans_num
    }
    return render(request, "coaches/dashboard.html", context)


@login_required(login_url="accounts:login")
@coach_required
def new_requests(request):
    coach = request.user
    new_requests = get_list_or_404(Plan, coach=coach, status=False)
    context = {
        "new_requests": new_requests
    }
    return render(request, "coaches/new_requests.html", context)


@login_required(login_url="accounts:login")
@coach_required
def create_plan(request, request_id):
    plan_obj = get_object_or_404(Plan, pk=request_id, coach=request.user)
    workouts = get_list_or_404(WorkoutItem)
    context = {
        "plan_id": plan_obj.pk,
        "plan_size": plan_obj.size,
        "plan_client": plan_obj.client,
        "plan_images": plan_obj.image,
        "plan_created_at": plan_obj.created_at,
        "workouts": workouts,
    }
    return render(request, "coaches/design_plan.html", context)


@csrf_exempt
# @coach_required
# def create_pdf(request):
#     # Data
#     data = json.loads(request.POST["workouts"])
#     plan_id = request.POST.get("plan_id")
#     plan_obj = get_object_or_404(Plan, pk=plan_id)
#     # Creating PDF file
#     html_string = render_to_string(
#         "coaches/workout_template.html", {"workouts": data})
#     print(html_string)
#     html = HTML(string=html_string)
#     result = html.write_pdf("report.pdf")
#     # Create http reponse
#     response = HttpResponse(content_type="application/pdf;")
#     response['Content-Disposition'] = 'attachment; filename="workout.pdf"'
#     # response["Content-Transfer-Encoding"] = "binary"
#     # with tempfile.NamedTemporaryFile(delete=True) as output:
#     #     output.write(result)
#     #     output.flush()
#     #     output = open(output.name, 'rb')
#     #     response.write(output.read())
#     return response
@csrf_exempt
def create_pdf(request):
    context = {
        "workouts": request.POST
    }
    print(request.POST)
    template = "coaches/workout_template.html"
    pdf = render_to_pdf(template, context)
    if pdf:
        response = HttpResponse(pdf, content_type="application/pdf")
        filename = "workout.pdf"
        content = "attachment; filename=%s" % filename
        # download = request.GET.get("download")
        # if download:
        content = "attachment; filename=%s" % filename
        response["Content-Disposition"] = content
        return response
    return HttpResponse("Not found.")


def render_to_pdf(template_src, context_dict={}):
    template = get_template(template_src)
    html = template.render(context_dict)
    result = BytesIO()
    pdf = pisa.pisaDocument(
        BytesIO(html.encode("UTF-8")), result, encoding="UTF-8")
    return HttpResponse(result.getvalue(), content_type='application/pdf')

coaches/templates/coaches/dashboard.html
{% extends 'base.html' %}
{% load static %}
{% block title_head %}پنل مربیان{% endblock title_head %}
{% block navbar %}
<nav class="navbar navbar-expand-lg bg-dark text-lg-right">
  <a class="navbar-brand" href="#">فیتنو | FITNO</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item d-inline-block">
        <a class="nav-link" href="#">صفحه اصلی</a>
      </li>
      <li class="nav-item d-inline-block">
        <a class="nav-link" href="{% url 'coaches:new_requests' %}">درخواست‌های جدید</a>
      </li>
      <li class="nav-item d-inline-block">
        <a class="nav-link" href="#">لیست کلاینت‌ها</a>
      </li>
    </ul>
  </div>
</nav>
{% endblock navbar %}
{% block content %}
    <div class="container mt-5">
        <div class="row my-5">
            <h2 class="text-danger">خوش آمدی مربی: {{request.user.first_name}}</h2>
        </div>
        <div class="row">
            <div class="col-md-4">
                <div class="bg-warning p-2">
                    <h4 class="text-center">برنامه‌های نوشته شده</h4>
                    <h1 class="text-center">{{ plans_num }}</h1>
                </div>
            </div>
            <div class="col-md-4">
                <div class="bg-warning p-2">
                    <h4 class="text-center">تعداد کلاینت‌ها</h4>
                    <h1 class="text-center">23</h1>
                </div>
            </div>
            <div class="col-md-4">
                <div class="bg-warning p-2">
                    <h4 class="text-center">روز‌های مربیگری</h4>
                    <h1 class="text-center">220</h1>
                </div>
            </div>
        </div>
        <div class="row mt-5">
            <div class="col-md-4">
                <ul class="listbox">
                    <img src="{{request.user.profile.coachprofileextra.image.url}}"/>
                </ul>
            </div>
            <div class="col-md-8">
              <form method="POST" action="{% url 'coaches:update_coach_information' %}" enctype="multipart/form-data">
              {% csrf_token %}
                  <div class="form-row">
                    <div class="form-group col-md-6">
                      <label for="inputFirstname">نام</label>
                      <input type="text" class="form-control" name="first_name" id="inputFirstname" value="{{ request.user.first_name }}">
                    </div>
                    <div class="form-group col-md-6">
                      <label for="inputLastname">نام خانوادگی</label>
                      <input type="text" class="form-control" name="last_name" id="inputLastname" value="{{ request.user.last_name }}">
                    </div>
                  </div>
                  <div class="form-row">
                    <div class="form-group col-md-6">
                      <label for="inputEmail4">ایمیل</label>
                      <input type="email" class="form-control" disabled id="inputEmail4" placeholder="" value="{{ request.user.email }}">
                    </div>
                    <div class="form-group col-md-6">
                      <label for="inputEdu">سطح تحصیلات</label>
                      <input type="text" class="form-control" id="inputEdu" name="education" placeholder="سطح تحصیلات" value="{{ request.user.profile.coachprofileextra.education }}">
                    </div>
                  </div>
                  <div class="form-row">
                    <div class="form-group col-md-6">
                      <label for="inputLocation">مکان</label>
                      <input type="text" class="form-control" name="location" id="inputLocation" placeholder="" value="{{ request.user.profile.location }}">
                    </div>
                    <div class="form-group col-md-6">
                      <label for="inputJob">شغل</label>
                      <input type="text" class="form-control" name="job" id="inputJob" placeholder="سطح تحصیلات" value="{{ request.user.profile.job }}">
                    </div>
                  </div>
                  <div class="form-row">
                    <div class="form-group col-md-6">
                      <label for="inputImage">عکس پروفایل</label>
                      <input type="file" class="form-control" name="image" id="inputImage" placeholder="" value="{{ request.user.profile.location }}">
                    </div>
                    <div class="form-group col-md-6">
                      <label for="inputPanelImage">عکس پنل</label>
                      <input type="file" class="form-control" name="panel_image" id="inputPanelImage" placeholder="سطح تحصیلات" value="{{ request.user.profile.job }}">
                    </div>
                  </div>
                  <h3 class="text-dark mt-3 d-inline-block">قیمت‌ها</h3>
                  <div class="p-3">
                    <div class="form-row">
                      <div class="form-group col-md-6">
                        <label for="inputWorkoutprice">برنامه تمرینی</label>
                        <input type="text" class="form-control" name="workout_price" id="inputWorkoutprice" value={{ request.user.coachextra.workout_price }}>
                      </div>
                      <div class="form-group col-md-6">
                        <label for="inputMealPrice">برنامه غذایی و مکمل</label>
                        <input type="text" class="form-control" name="meal_price" id="inputMealPrice" value={{ request.user.coachextra.meal_price }}>
                      </div>
                    </div>
                  </div>
                  <button type="submit" class="btn btn-primary">ثبت</button>
              </form>
            </div>
        </div>
    </div>
{% endblock content %}

coaches/templates/coaches/design_plan.html
{% extends 'base.html' %}
{% block title_head %}پنل مربیان{% endblock title_head %}
{% block navbar %}
<nav class="navbar navbar-expand-lg bg-dark text-lg-right">
  <a class="navbar-brand" href="#">فیتنو | FITNO</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item d-inline-block">
        <a class="nav-link" href="{% url 'coaches:dashboard' %}">صفحه اصلی</a>
      </li>
      <li class="nav-item d-inline-block">
        <a class="nav-link" href="{% url 'coaches:new_requests' %}">درخواست‌های جدید</a>
      </li>
      <li class="nav-item d-inline-block">
        <a class="nav-link" href="#">لیست کلاینت‌ها</a>
      </li>
    </ul>
  </div>
</nav>
{% endblock navbar %}

{% block content %}
<div class="container mt-5">
  <div class="row">
      <div class="col-md-12">
        <p class="text-dark p-1">مشخصات کلاینت</p>
        <table class="table table-striped">
            <thead>
                <tr>
                    <th scope="col">نام کامل</th>
                    <th scope="col">شغل</th>
                    <th scope="col">محل زندگی</th>
                    <th scope="col">تاریخ ثبت درخواست</th>
                </tr>
            </thead>
            <tbody>
              <tr class="text-center">
                  <td>{{ plan_client.first_name }} {{ plan_client.last_name }}</td>
                  <td>{{ plan_client.profile.job }}</td>
                  <td>{{ plan_client.profile.location }}</td>
                  <td>{{ plan_created_at }}</td>
              </tr>
            </tbody>
          </table>
      </div>
  </div>
  <div class="row">
    <div class="col-md-9">
      <p class="text-dark p-1">سایزهای کلاینت</p>
      <table class="table">
        <thead class="thead-dark">
          <tr>
            <th scope="col">قد</th>
            <th scope="col">وزن</th>
            <th scope="col">گردن</th>
            <th scope="col">سینه</th>
            <th scope="col">بازو</th>
            <th scope="col">مچ</th>
            <th scope="col">کمر</th>
            <th scope="col">همسترینگ</th>
            <th scope="col">ساق</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <th scope="row">{{ plan_size.height }}</th>
            <th scope="row">{{ plan_size.weight }}</th>
            <th scope="row">{{ plan_size.neck }}</th>
            <th scope="row">{{ plan_size.chest }}</th>
            <th scope="row">{{ plan_size.arm }}</th>
            <th scope="row">{{ plan_size.wrist }}</th>
            <th scope="row">{{ plan_size.waist }}</th>
            <th scope="row">{{ plan_size.hamstring }}</th>
            <th scope="row">{{ plan_size.calf }}</th>
          </tr>
        </tbody>
      </table>
      <hr />
      <div class="row">
        <div class="col-md-9">
          <div class="plan-inputs">
            <form class="form-group" method="POST" action="{% url 'coaches:create_pdf' %}">{% csrf_token %}
              <div class="form-inputs"></div>
             <div class="d-flex justify-content-end">
                <button type="submit" class="btn btn-success btnCreatePlan mt-3 text-white">صدور برنامه</button>
             </div>
            </form>
          </div>
        </div>
        <div class="col-md-3">
          <ul class="list-group">
            {% for workout in workouts %}
              <li class="list-group-item d-inline-block" id="{{ workout.pk }}">{{ workout.title }}</li>
            {% endfor %}
          </ul>
        </div>
      </div>
    </div>
    <div class="col-md-3">
      <p class="text-dark p-1">عکس‌های کلاینت</p>
      <p class="text-light mb-1 p-1 bg-info">از جلو: </p>
      <img src="{{ plan_images.front.url }}"/>
      <p class="text-light mb-1 p-1 bg-info">از کنار: </p>
      <img src="{{ plan_images.side.url }}"/>
      <p class="text-light mb-1 p-1 bg-info">از پشت: </p>
      <img src="{{ plan_images.back.url }}"/>
    </div>
  </div>

</div>

{% endblock content %}

coaches/templates/coaches/new_requests.html
{% extends 'base.html' %}
{% block title_head %}پنل مربیان{% endblock title_head %}
{% block navbar %}
<nav class="navbar navbar-expand-lg bg-dark text-lg-right">
  <a class="navbar-brand" href="#">فیتنو | FITNO</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item d-inline-block">
        <a class="nav-link" href="{% url 'coaches:dashboard' %}">صفحه اصلی</a>
      </li>
      <li class="nav-item d-inline-block">
        <a class="nav-link" href="#">درخواست‌های جدید</a>
      </li>
      <li class="nav-item d-inline-block">
        <a class="nav-link" href="#">لیست کلاینت‌ها</a>
      </li>
    </ul>
  </div>
</nav>
{% endblock navbar %}
{% block content %}
    <div class="container mt-5">
        <div class="row">
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">نام کامل</th>
                        <th scope="col">تاریخ ثبت درخواست</th>
                        <th scope="col">عملیات</th>
                    </tr>
                </thead>
                <tbody>
                    {% for request in new_requests %}
                        <tr class="text-center">
                            <th scope="row">{{ forloop.counter }}</th>
                            <td>{{ request.client.first_name }} {{ request.client.last_name }}</td>
                            <td>{{ request.created_at }}</td>
                            <td><a href="{% url 'coaches:create_plan' request_id=request.pk %}" class="btn btn-info text-light">طراحی برنامه</a></td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock content %}

coaches/templates/coaches/workout_template.html
{% load static %}

<html>
 <head>
   <title>Test</title>
   <style>
     h1 {
       text-align: center;
     }

     table {
       border: 1px solid;
       margin: 0 auto;
       width: 70%;
     }

     td, th {
       text-align: center;
       border: 1px solid;
     }
   </style>
 </head>
 <body>
  {% comment %} <div class="image-holder">
    <img class="rounded" src="{% static 'workout_template/pdf-image.jpg' %}"/>
  </div> {% endcomment %}
   <h1>لیست حرکات</h1>
   <table>
     <thead>
       <tr>
         <th>نام حرکت</th>
         <th>تعداد ست</th>
       </tr>
     </thead>
     <tbody>
       {% for w in workouts %}
         <tr>
           <td>{{ w.name }}</td>
           <td>{{ w.set }}</td>
         </tr>
       {% endfor %}    
     </tbody>
   </table>
 </body>
</html>